version: "3.8"
services:
  web:
    build:
      context: .
    command: sh -c "npm start"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    # ports:
    #   - "3000:3000"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
