version: "3.8"
services:
  redis:
    image: redis:7-alpine
  
  postgres:
    image: postgres:16-alpine
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # restart: unless-stopped

  web:
    build:
      context: .
    command: npm run dev
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"

volumes:
  postgres_data:
